typography_spectrum: 0.11454869201406837
color:
  brandStrength: 0.4964063751976937
  lightness: 0.1041486298199743
  saturation: 0.8030486495699733
  rhythmicContrast: 0.8317538783885539
  brandColors:
    - '#25064D'
    - '#36175E'
    - '#553285'
    - '#7B52AB'
    - '#9768D1'
layout_spectrum: 0.7300242357887328
author:
  name: Peggy Carpenter
  email: peggyleecarpenter@gmail.com
  url: peggyleecarpenter.com
name: peggyiswriting
navigation:
  - id: 'http://peggyleecarpenter.com'
    url: 'http://peggyleecarpenter.com'
    name: My Existing Site
    type: external
